export enum PermissionEnum {
  // categoties
  VIEW_CATEGORY = 'VIEW_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  TEST_CATEGORY = 'TEST_CATEGORY',
}
